name: Build
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build . -t local

      - name: Test Python version
        run: docker run local /bin/sh -- python --version

      - name: Test CMake version
        run: docker run local /bin/sh -- cmake --version

      - name: Test ARM compiler version
        run: docker run local /bin/sh -- arm-none-eabi-gcc --version
