name: Build
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t local
